// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyowmDMXFyam64FKY7oHS6_HN1HS5h1lU',
    appId: '1:149544505550:web:5d0bed83b176eb4be7809f',
    messagingSenderId: '149544505550',
    projectId: 'brain-tumor-3a1dd',
    authDomain: 'brain-tumor-3a1dd.firebaseapp.com',
    storageBucket: 'brain-tumor-3a1dd.appspot.com',
    measurementId: 'G-7B4WR9Q9GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Cuqqkyqda1d2-K5l3lem6VPhqLWe3VQ',
    appId: '1:149544505550:android:bef9170a024a8682e7809f',
    messagingSenderId: '149544505550',
    projectId: 'brain-tumor-3a1dd',
    storageBucket: 'brain-tumor-3a1dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCskYscFLDgnIYBbBMAysJVI8yPLTQx8',
    appId: '1:149544505550:ios:b4e320207b16ebc0e7809f',
    messagingSenderId: '149544505550',
    projectId: 'brain-tumor-3a1dd',
    storageBucket: 'brain-tumor-3a1dd.appspot.com',
    iosBundleId: 'com.example.brainTumor',
  );
}
